volumes:
  grafana_storage:
    driver: local
  prometheus_data:
    driver: local

networks:
  kelompok2_network:
    driver: bridge

services:
  express-api:
    build: ./express-api
    networks:
      - kelompok2_network
    ports:
      - "3001:3000"

  nginx:
    build: ./nginx
    networks:
      - kelompok2_network
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

  php-fpm:
    build: ./php-fpm
    networks:
      - kelompok2_network
    volumes:
      - ./php-fpm:/var/www/html

  prometheus:
    build: ./prometheus
    networks:
      - kelompok2_network
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/etc/prometheus

  grafana:
    build: ./grafana
    networks:
      - kelompok2_network
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_storage:/var/lib/grafana
    restart: unless-stopped
    depends_on:
      - prometheus

  # db:
  #   build: ./postgresql
  #   networks:
  #     - kelompok2_network
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     TSTUNE_PROFILE: promscale
  #   ports:
  #     - "5432:5432"

  # promscale:
  #   build: ./promscale
  #   networks:
  #     - kelompok2_network
  #   environment:
  #     PROMSCALE_DB_URI: postgres://postgres:password@db:5432/postgres?sslmode=allow
  #     PROMSCALE_TRACING_OTLP_SERVER_ADDRESS: ":9202"
  #     PROMSCALE_TELEMETRY_TRACE_SAMPLING_RATIO: "0.1"
  #     PROMSCALE_METRICS_RULES_CONFIG_FILE: ./prometheus/prometheus.yml
  #   ports:
  #     - "9201:9201"
  #     - "9202:9202"
  #   depends_on:
  #     - db
  #   restart: on-failure

  # prometheus-postgresql-adapter:
  #   build: ./prometheus-postgresql-adapter
  #   networks:
  #     - kelompok2_network
  #   environment:
  #     TS_PROM_LOG_LEVEL: debug
  #     TS_PROM_PG_DB_CONNECT_RETRIES: 10
  #     TS_PROM_PG_HOST: postgresql
  #     TS_PROM_PG_PASSWORD: postgres
  #     TS_PROM_PG_SCHEMA: postgres
  #     TS_PROM_WEB_TELEMETRY_PATH: /metrics-text
  #   ports:
  #     - "9201:9201"