global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "express-api"
    static_configs:
      - targets: ["express-api:3000"]
    metrics_path: /metrics

  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    metrics_path: /metrics

  - job_name: "php"
    static_configs:
      - targets: ["php:9000"]
    metrics_path: /metrics

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]

  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "grafana"
