global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "express-api"
    static_configs:
      - targets: ["express-api:3000"]

  - job_name: "php-api"
    static_configs:
      - targets: ["php-api:80"]

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]

remote_write:
  - url: "http://prometheus-postgresql-adapter:9201/write"
